# Generated by Django 4.2 on 2023-04-30 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('first_line', models.IntegerField()),
                ('last_line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileSectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'compiles without warnings'), ('WC', 'compiles with warnings'), ('NC', 'does not compile')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FileSystemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('availability', models.BooleanField(default=True)),
                ('availability_change_date', models.DateTimeField(blank=True, verbose_name='date of last availability change')),
                ('content_change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of last content change')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('filesystemobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_ide.filesystemobject')),
            ],
            bases=('web_ide.filesystemobject',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('filesystemobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_ide.filesystemobject')),
            ],
            bases=('web_ide.filesystemobject',),
        ),
        migrations.AddField(
            model_name='filesystemobject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ide.user'),
        ),
        migrations.CreateModel(
            name='FileSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROC', 'procedure'), ('COMM', 'comment'), ('COMP_DIR', 'compiler directive'), ('VAR_DEC', 'variable declaration'), ('ASM_CODE', 'assembly code')], max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ide.filesection')),
            ],
        ),
        migrations.CreateModel(
            name='FileSectionStatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ide.filesection')),
            ],
        ),
        migrations.AddField(
            model_name='filesystemobject',
            name='parent_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_ide.directory'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ide.file'),
        ),
    ]
