# Generated by Django 4.2 on 2023-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemobject',
            name='availability_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of last availability change'),
        ),
    ]
