# Generated by Django 4.2 on 2023-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ide', '0003_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, default="// this is content of file <class 'super'>"),
        ),
    ]
