# Generated by Django 4.2 on 2023-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ide', '0005_alter_filesystemobject_owner_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='compiled_content',
            field=models.TextField(blank=True, default="// this is compiled content of file <class 'super'>"),
        ),
    ]
